### ISSUE TITLE
Exception when open lucene index (created by java lucene) for ZF-1.12.20

### ISSUE THREAD

**Issue by vishalsharnagat** [zendframework/zend-server#23]
I am creating search index in java with Lucene 1.9.1 (available in eclipse 3.6.2) and using search from PHP 5.2 code & Zend Framework 1.8.2. I do get expected search results.

I am in process to upgrade eclipse to 4.2.2 which has Lucene 2.9.1 used for index creation. I also upgraded PHP to 7.1 and Zend Framework to 1.12.20. But now I get below error:

Fatal error: Uncaught Zend_Search_Lucene_Exception: Unsupported segments 
file format in C:\xampp1\php\pear\Zend\Search\Lucene.php:422 Stack trace: #0 
C:\xampp1\php\pear\Zend\Search\Lucene.php(570): Zend_Search_Lucene-
>_readSegmentsFile() #1 C:\xampp1\php\pear\Zend\Search\Lucene.php(225): 
Zend_Search_Lucene->__construct('C:\\xampp1\\htdoc...', false) #2 
C:\xampp1\htdocs\openup_Classic\search\SearchContext.php(89): 
Zend_Search_Lucene::open('C:\\xampp1\\htdoc...') #3 
C:\xampp1\htdocs\openup_Classic\search\SearchContext.php(50): SearchContext-
>_doSearch() #4 C:\xampp1\htdocs\openup_Classic\search\PHPSearch.php(28): 
SearchContext->__construct('http://localhos...', 'role', '10') #5 {main} 
thrown in C:\xampp1\php\pear\Zend\Search\Lucene.php on line 422

I guess the issue may be that index are created with java lucene 2.9.1 but PHP code or Zend framework is still using old lucene 1.9.1. If the index are created with lucene 1.9.1, it gives proper search result.

Could you please help me to identify the exact root cause for above exception and probable solution to overcome the error?

Thanks in advance.

**Comment by Ocramius** [comment]
ZF1 is no longer supported, sorry.
