### ISSUE TITLE
Disabling Z-Ray from zend server interface doesn't disable it for the CLI

### ISSUE THREAD

**Issue by DanTalash** [zendframework/zend-server#28]
When disabling Z-Ray from the zend server UI, I noticed that it was still enabled for the CLI.

## Reproducing issue

* Log in to the Zend Server interface.
* Go into the Z-Ray -> Mode menu on the sidebar.
* Select the _'Disabled'_ radio button.
* Save and restart server, as appropriate.

### Expected results

Z-Ray is disabled for web requests and the CLI.

### Actual results

Z-Ray only gets disabled for web requests, but is still enabled for the CLI. 

Examining `/usr/local/zend/etc/conf.d/zray.ini` shows that `zray.enable` is set to 0, but `zray.enable_cli` is still set to 1. This currently needs to be manually changed to disable Z-Ray for the CLI.

**Comment by Xerkus** [comment]
This is php package from Zend Framework and it is not related to a product Zend Server.

**Comment by DanTalash** [comment]
Sorry, the names are very similar and it's the first google result. Thanks for the quick response.
